import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const LINKS = [{ title: 'Text', href: '/'},
{ title: 'Heading', href: '/' },
{ title: 'Paragraphs', href: '/' },
{ title: 'List', href: '/' },
{ title: 'Horizontal rules', href: '/' },
{ title: 'Tabular data', href: '/' },
{ title: 'Code', href: '/' },
{ title: 'Inline elements', href: '/' },]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar links={LINKS} />
        {children}
      </body>
    </html>
  );
}
