import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar/index";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const LINKS = [{ title: 'Text', href: '#text' },
{ title: 'Heading', href: '#heading' },
{ title: 'Paragraphs', href: '#paragraph' },
{ title: 'Blockquotes', href: '#blockquotes' },
{ title: 'List', href: '#lists' },
{ title: 'Horizontal rules', href: '#horizontal-rules' },
{ title: 'Tabular data', href: '#tabular-data' },
{ title: 'Code', href: '#code' },
{ title: 'Inline elements', href: '#inline-elements' },]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar links={LINKS} />
        {children}
      </body>
    </html>
  );
}
